### PR TITLE
Add GitHub Pages for browsing documentation

### PR DESCRIPTION
**Pull request by earthpyy**
## Preview

[here](https://c0d1um.github.io/technical-standard/)

## Changes

- Add GitHub Pages
- Add auto-generated ToC
- Remove hard-coded ToC in _Model_ page
- Move _PyCharm Configuration_ section into its section
- Re-level topics in _ViewSets_ page

### CODE REVIEW

**Comment by powerdefy** [comment]
Have some conflicts krub.

**Comment by earthpyy** [comment]
#6 #7

**Comment by earthpyy** [comment]
> Have some conflicts krub.

Solved krubb.

**Review by powerdefy — APPROVED** [review]
good krub

**Comment by NorakGithub** [comment]
@earthpyy Should we add contribute instruction na krub for auto generate ToC? Also could we choose font for code format na? It's look like from old machine.

**Comment by earthpyy** [comment]
> @earthpyy Should we add contribute instruction na krub for auto generate ToC? Also could we choose font for code format na? It's look like from old machine.

Yes, I'm agree with you krub. Next step I'll write a contribution guide krub. And about theme, can we change to something else krab? @powerdefy

**Review by NorakGithub — APPROVED** [review]

**Pull request merged**
