### PR TITLE
Django - Third-Party Library Guideline

### PR DESCRIPTION
**Pull request by NorakGithub**

### CODE REVIEW

**Review by powerdefy — APPROVED** [review]
Good krub

**Review by earthpyy — COMMENTED** [review]
I'd like to add

- `django-sequences`: Sequence generator
- `celery`
- `redis` (?)
- `sentry-sdk`
- `djangorestframework-api-key`: Great for implementing API key
- `drf-spectacular`: For Swagger API documentation generation

What do you think about each of them krub?

**Comment by NorakGithub** [comment]
@earthpyy Will add krub

**Review by piyapan039285 — APPROVED** [review]
ok krub

**Pull request merged**
