### PR TITLE
Add Project Structure section and enhancement

### PR DESCRIPTION
**Pull request by earthpyy**
## Enhancement
- Create `django` directory
- Add default `README.md` in `django` directory

## Changes
- Add **Project Structure** section

### CODE REVIEW

**Review by powerdefy — APPROVED** [review]
Look good

**Review by NorakGithub — APPROVED** [review]
Great Job!

**Comment by NorakGithub** [comment]
I request `services` for code that connect to third party services, `manager` for reusable queryset with Django Manager.

**Comment by NorakGithub** [comment]
> I request `services` for code that connect to third party services, `manager` for reusable queryset with Django Manager.

Oh you already have manager file, so only `services.py`

**Review by piyapan039285 — APPROVED** [review]
Good krub.

**Comment by earthpyy** [comment]
Thank you all krubbb P'

**Pull request merged**
