### PR TITLE
Add Gitflow Workflow into Git Flow DevOps standard

### PR DESCRIPTION
**Pull request by earthpyy**
Here's a flow selection diagram to review krub:

Flow selection

### CODE REVIEW

**Comment by NorakGithub** [comment]
@earthpyy I have question regarding with related to Switch krub. In Switch any commit directly to master will be ignored, because we won't be able to track what is it about, so I think in the future we will not allow people to push directly to master so Centralize Workflow won't be using anymore.

**Comment by earthpyy** [comment]
> @earthpyy I have question regarding with related to Switch krub. In Switch any commit directly to master will be ignored, because we won't be able to track what is it about, so I think in the future we will not allow people to push directly to master so Centralize Workflow won't be using anymore.

Updated krubbb @NorakGithub

**Review by NorakGithub — APPROVED** [review]
Great!

**Review by powerdefy — APPROVED** [review]
Good

**Pull request merged**
